### ISSUE TITLE
Dynamic memory allocation

### ISSUE THREAD

**Issue by vessi** [mrubyc/mrubyc#10]
I want to start a discussion here about usage of dynamic memory allocation.

According to `static.c` currently we are allocating ~30Kb statically using config variables provided in `vm_config.h`.

I suggest to change static memory allocation to dynamic memory allocation so we will use less RAM.
This will require to implement `_sbrk` function on every platform to use `malloc.h` functions. The simplest sample (I've created it for TI Tiva-C board) goes below:

``` c
extern unsigned long _heap_bottom;
extern unsigned long _heap_top;
char *heap_end = (caddr_t)&_heap_bottom;

caddr_t _sbrk(unsigned int inc) {
  static char *prev_heap_end;
  if (heap_end == 0) {
    heap_end = (caddr_t)&_heap_bottom;
  }
  prev_heap_end = heap_end;
  if (heap_end + inc > (caddr_t)&_heap_top) {
    return (caddr_t)0;
  }
  heap_end += inc;
  return (caddr_t)prev_heap_end;
}
```

`_heap_bottom` and `_heap_top` are segments from ld script for this board (you can take a look on it [here](https://github.com/vessi/mrubyc/blob/develop/tiva-c%2Ftiva-c.ld)).

This will also require to implement simple GC to free memory if it's needed. Anyhow, now memory consumption is on it's max level.

What do you think?

**Comment by xor256** [comment]
1. What is target procesors? for example Arduino?
2. Many library for small processor have no malloc function
3. Is possible to using more function? malloc for allocating free for free ;-) get_pointer for seting memory pointer mem_delete for deleting object (for example using only once)
In many processors memory is extremely small. if get_pointer function appear in future we will create compress memory or memory in separate place (swap,SD disk)

**Comment by vessi** [comment]
1. For example, I've successfully launched it on Texas Instruments Tiva-C board with 32K of RAM and 80MHz of CPU clock. I think it can be easily reimplemented for any platform supported by GCC.
2. `malloc` is standard part of libc, so if you have GCC for your target - you already have malloc.
3. Sorry, didn't get your point.

**Comment by xor256** [comment]
3. Its simple example:
Processor have small memory but have i2c or other interface to using SD card, encrypted memory or other fastest RAM, swap. But this memory is not linear with main memory. How using it?

**Comment by vessi** [comment]
In this case you only need to re-implement your own logic for `_sbrk` function which lies on background for every `malloc`, `calloc` and `realloc` function. In any case memory should be plain-addressed to be accessible by MCU, isn't it?

**Comment by texrg** [comment]
http://www.cpu-world.com/CPUs/TMS7000/index.html not have mcu

**Comment by vessi** [comment]
well, code of mruby/c requires 32 bits to be supported. I think it's impossible to run mruby/c on 8-bit controller.

**Comment by kaz0505** [comment]
because mruby/c on 8bit processor is hard to implement, I suppose that the target processor is 16bit and 32bit.

back to the dynamic memory allocation, do you know any appropriate algorithm for mruby/c?
some of 16 bit processors do not have mcu, mruby/c should be memory management without mcu.

**Comment by vessi** [comment]
The easiest way in this case will be to implement both ways and do this configurable via `vm_config.h` constants.

**Comment by kaz0505** [comment]
I agree.

I'll check an alternative memory allocation method for mruby/c.

**Comment by kaz0505** [comment]
We, mruby/c developers, discuss about reference count algorithm for dynamic memory allocation.
In mruby/c, unused memory block should be collected by VM.
And memory fragmentation problem may be occur.

**Comment by texrg** [comment]
two solution:
a) special macros for get_pointer from memory
p = malloc(sizeof(int));
get_memory(*p) = 5;
b) or pointer is not a index in memory but is a pointer to pointer.
every pointer is only index in array of pointer (proxy memory? I dont know how it is in english)

Another alternative is agreeing to the fragmentation on simple processors

**Comment by kaz0505** [comment]
the idea pointer to pointer, aka handle, can solve the memory fragmentation and relocation with some overhead. 

mruby/c does not provide GC now. My idea is,,,
GC at OP_STOP execution, which stops VM. All the memory block will be collected at this time.
In VM execution, memory block is not collected dynamically instead. 
I have concern about "out of memory"

**Comment by vessi** [comment]
in this case calling GC is better on each `OP_RETURN` too maybe?

**Comment by texrg** [comment]
GC not solve fragmentation memory. To many references to objects, to big output vm code, to slow.
I m afraid thinking about threads and real time aplications or network.
ii) idea is fast and easy to change in future.

is possible to mixing i) and ii)
using virtual memory different to physics memory.

**Comment by kaz0505** [comment]
GC at OP_RETURN is good idea! Thank you.
And I try to implement pointer to pointer memory allocation.
I'll prepare a branch for this purpose.

**Comment by texrg** [comment]
if GC is planing please add GS.start .disable or meybe .define_finalizer  but not in ObjectSpace. Meybe in GC? Any other idea to know when object was destroyed?
ObjectSpace is not necessary

**Comment by xor256** [comment]
in errorcode.h meyby add

`#define VM_EXEC_ERROR_MALLOC             (VM_EXEC_ERROR | 0x0004)`
or other errors for mrb_obj_alloc()

**Comment by kaz0505** [comment]
I think VM_EXEC_ERROR_MALLOC is appropriate.

**Comment by texrg** [comment]
Meybe writing wrapper to normal memory and using it. In next time writing new dynamic memory library? For example glib or system have normal memory usage. We will would refer to our benchmarks.

**Comment by kaz0505** [comment]
My trial of dynamic memory allocation at https://github.com/kaz0505/mruby_malloc_evaluate is for simple GC.
Each allocated memory block has a reference counter.
In current implementation of mruby/c, a vm uses static array, but it causes unused memory. 

I'll try to apply this reference counter GC to mruby/c, and evaluate it.

**Comment by kaz0505** [comment]
I'll update mruby/c source codes, which contains dynamic memory allocation.
This update realizes automatic memory release when one vm is closed.

**Comment by kaz0505** [comment]
TLSF memory allocation is implented, which is default memory allocation functions in mruby/c.
