### ISSUE TITLE
MRB_TT_NIL

### ISSUE THREAD

**Issue by kaz0505** [mrubyc/mrubyc#12]
Is MRB_TT_NIL necessary?

Although nil is different from false, that is same behavior in conditional expression.

**Comment by texrg** [comment]
I think yes

**Comment by vessi** [comment]
I see no sense in adding separate type for `nil` values. We can avoid any complication just by adding corresponding macro to detect if `mrb_value` is nil.

**Comment by texrg** [comment]
@vessi How You write this function?
`false.nil?`
`Object.new.nil?`
exist NilClass ? Why not MRB_TT_NIL ?

**Comment by vessi** [comment]
take a look how it's implemented in mruby: https://github.com/mruby/mruby/blob/master/include/mruby/boxing_word.h#L108

yes, we can separate `MRB_TT_NIL` to keep types consistent but in this case we should use naming like `MRB_TT_BOOL`, not `MRB_TT_TRUE`.

**Comment by xor256** [comment]
Can You show me which solution is better?
Better memory usage?
Better faster running?
 How to make a good decision?

**Comment by vessi** [comment]
@xor256 my starting point was to keep similarity of codebase with mruby as much as it's possible

**Comment by xor256** [comment]
@vessi 
set of criteria is important.

**Comment by kaz0505** [comment]
both MRBC_TT_NIL and MRBC_TT_FALSE was prepared.
nil? method was also implemented.
