### ISSUE TITLE
Which branch should I pull request on?

### ISSUE THREAD

**Issue by ccmywish** [mrubyc/mrubyc#125]
I find the branch `mrubyc3.1` is under active development, but I can't test it using `mrubyc-test` on account of some bugs which I can't fix for now.  I'm not using docker, instead I just install `mrubyc-test` gem directly . 

However, I can test the master branch well, and I've already implemented some lacking pieces of the code.  Can I pull request on the `master` branch?

**Comment by hasumikin** [comment]
@ccmywish Could you push your branch to ccmywish/mrubyc  so that we can see it? If it looks able to be merged into master regarding our current development strategy, we are happy to do it. Even if not, we will be willing to find a good way to solve a problem

**Comment by ccmywish** [comment]
@hasumikin Hi, I've pulled a request here #126
