### ISSUE TITLE
Please write documentation

### ISSUE THREAD

**Issue by texrg** [mrubyc/mrubyc#13]
Please write me small documentation. 
For example one function, one ruby opcodes
but with information how get arguments, how return numbers or symbols
small information for developers.

BTW is possible to create web page width information how many opcodes ist and how many need to write

**Comment by kaz0505** [comment]
Currently we provide few document, I'm sorry.
Would you contribute documents?
How about documents on wiki ?

**Comment by vessi** [comment]
Definitely we need some documentation. I am ready to write next documents:

1. Format of MRB byte code file
1. Table of opcodes together with description of their meanings and format of arguments

**Comment by kaz0505** [comment]
The simple structure of MRB byte code is ready. 
I add a bytecode_format.md in doc folder.

**Comment by xor256** [comment]
@kaz0505
What is 'pool' in irep ?
in header CRC is crc16 or other?
can You writing which value is unsigned?
