### ISSUE TITLE
opcode

### ISSUE THREAD

**Issue by xor256** [mrubyc/mrubyc#15]
Hello,
I'm not sure. Is it all opcodes ?

---------
#opcode##
;1;OP_NOP;0x00;
;1;OP_MOVE;0x01;
;1;OP_LOADL;0x02;
;1;OP_LOADI;0x03;
;0;OP_LOADSYM;
;1;OP_LOADNIL;0x05;
;1;OP_LOADSELF;0x06;
;1;OP_LOADT;0x07;
;1;OP_LOADF;0x08;
;1;OP_GETGLOBAL;0x09;
;1;OP_SETGLOBAL;0x0a;
;0;OP_GETSPECIAL;
;0;OP_SETSPECIAL;
;0;OP_GETIV;
;0;OP_SETIV;
;0;OP_GETCV;
;0;OP_SETCV;
;0;OP_GETMCNST;
;0;OP_SETMCNST;
;0;OP_GETUPVAR;
;0;OP_SETUPVAR;
;1;OP_GETCONST;0x11;
;1;OP_SETCONST;0x12;
;1;OP_JMP;0x17;
;1;OP_JMPIF;0x18;
;1;OP_JMPNOT;0x19;
;0;OP_ONERR;
;0;OP_RESCUE;
;0;OP_POPERR;
;0;OP_RAISE;
;0;OP_EPUSH;
;0;OP_EPOP;
;1;OP_SEND;0x20;
;0;OP_SENDB;
;0;OP_FSEND;
;0;OP_CALL;
;0;OP_SUPER;
;0;OP_ARGARY;
;1;OP_ENTER;0x26;
;0;OP_KARG;
;0;OP_KDICT;
;1;OP_RETURN;0x29;
;0;OP_TAILCALL;
;0;OP_BLKPUSH;
;1;OP_ADD;0x2c;
;1;OP_ADDI;0x2d;
;1;OP_SUB;0x2e;
;1;OP_SUBI;0x2f;
;0;OP_MUL;
;0;OP_DIV;
;1;OP_EQ;0x32;
;1;OP_LT;0x33;
;1;OP_LE;0x34;
;1;OP_GT;0x35;
;1;OP_GE;0x36;
;1;OP_ARRAY;0x37;
;0;OP_ARYCAT;
;0;OP_ARYPUSH;
;0;OP_AREF;
;0;OP_ASET;
;0;OP_APOST;
;0;OP_STRING;
;0;OP_STRCAT;
;0;OP_HASH;
;1;OP_LAMBDA;0x40;
;0;OP_RANGE;
;0;OP_OCLASS;
;1;OP_CLASS;0x43;
;0;OP_MODULE;
;0;OP_EXEC;
;1;OP_METHOD;0x46;
;0;OP_SCLASS;
;1;OP_TCLASS;0x48;
;0;OP_DEBUG;
;1;OP_STOP;0x4a;
;0;OP_ERR;
;0;OP_RSVD1;
;0;OP_RSVD2;
;0;OP_RSVD3;
;0;OP_RSVD4;
;0;OP_RSVD5;

---------

**Comment by texrg** [comment]
All opcodes is 36 and 58% is writed ;-)

**Comment by kaz0505** [comment]
They are methods.
op-codes are each instruction code in mruby byte code, such as OP_LOAD, OP_SEND and so on.
Some of methods are implemented as op-codes, for instance, + is implemented as OP_ADD and OP_ADDI. 

mruby has 81 op-codes. Although mruby/c should support same number of op-code, 33 op-codes are implemented now.

**Comment by xor256** [comment]
Can You write similar file which opcodes are implemented?

**Comment by xor256** [comment]
http://bankfotek.pl/image/1999273

**Comment by kaz0505** [comment]
Thank you.

matz and some of  mruby developers are planning about op-code refinement. 
some of the mruby op-codes are defined but not used.
This weekend I'll discuss with matz about this op-code refinement.
