### ISSUE TITLE
suport windows ??????

### ISSUE THREAD

**Issue by lingbl** [mrubyc/mrubyc#162]
I compile on windows MINGW64 , but fail

windows do not have SIGALRM ???

$ make all
cd mrblib ; make all
make[1]: Entering directory '/home/jling/mrubyc/mrubyc-release3.1/mrblib'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/jling/mrubyc/mrubyc-release3.1/mrblib'
cd src ; make all
make[1]: Entering directory '/home/jling/mrubyc/mrubyc-release3.1/src'
cc -DMRBC_USE_HAL_POSIX -Wall -Wpointer-arith -g     -c -o hal_posix/hal.o hal_posix/hal.c
In file included from hal_posix/hal.c:23:
hal_posix/hal.h: In function 'hal_flush':
hal_posix/hal.h:95:10: warning: implicit declaration of function 'fsync' [-Wimplicit-function-declaration]
   95 |   return fsync(1);
      |          ^~~~~
hal_posix/hal.c: At top level:
hal_posix/hal.c:32:8: error: unknown type name 'sigset_t'
   32 | static sigset_t sigset_, sigset2_;
      |        ^~~~~~~~
hal_posix/hal.c: In function 'hal_init':
hal_posix/hal.c:63:3: warning: implicit declaration of function 'sigemptyset' [-Wimplicit-function-declaration]
   63 |   sigemptyset(&sigset_);
      |   ^~~~~~~~~~~
hal_posix/hal.c:64:3: warning: implicit declaration of function 'sigaddset' [-Wimplicit-function-declaration]
   64 |   sigaddset(&sigset_, SIGALRM);
      |   ^~~~~~~~~
hal_posix/hal.c:64:23: error: 'SIGALRM' undeclared (first use in this function); did you mean 'SIGABRT'?
   64 |   sigaddset(&sigset_, SIGALRM);
      |                       ^~~~~~~
      |                       SIGABRT
hal_posix/hal.c:64:23: note: each undeclared identifier is reported only once for each function it appears in
hal_posix/hal.c:67:20: error: storage size of 'sa' isn't known
   67 |   struct sigaction sa;
      |                    ^~
hal_posix/hal.c:69:19: error: 'SA_RESTART' undeclared (first use in this function)
   69 |   sa.sa_flags   = SA_RESTART;
      |                   ^~~~~~~~~~
hal_posix/hal.c:71:3: warning: implicit declaration of function 'sigaction' [-Wimplicit-function-declaration]
   71 |   sigaction(SIGALRM, &sa, 0);
      |   ^~~~~~~~~
hal_posix/hal.c:74:20: error: storage size of 'tval' isn't known
   74 |   struct itimerval tval;
      |                    ^~~~
hal_posix/hal.c:81:3: warning: implicit declaration of function 'setitimer' [-Wimplicit-function-declaration]
   81 |   setitimer(ITIMER_REAL, &tval, 0);
      |   ^~~~~~~~~
hal_posix/hal.c:81:13: error: 'ITIMER_REAL' undeclared (first use in this function)
   81 |   setitimer(ITIMER_REAL, &tval, 0);
      |             ^~~~~~~~~~~
hal_posix/hal.c:74:20: warning: unused variable 'tval' [-Wunused-variable]
   74 |   struct itimerval tval;
      |                    ^~~~
hal_posix/hal.c:67:20: warning: unused variable 'sa' [-Wunused-variable]
   67 |   struct sigaction sa;
      |                    ^~
hal_posix/hal.c: In function 'hal_enable_irq':
hal_posix/hal.c:92:3: warning: implicit declaration of function 'sigprocmask' [-Wimplicit-function-declaration]
   92 |   sigprocmask(SIG_SETMASK, &sigset2_, 0);
      |   ^~~~~~~~~~~
hal_posix/hal.c:92:15: error: 'SIG_SETMASK' undeclared (first use in this function)
   92 |   sigprocmask(SIG_SETMASK, &sigset2_, 0);
      |               ^~~~~~~~~~~
hal_posix/hal.c: In function 'hal_disable_irq':
hal_posix/hal.c:103:15: error: 'SIG_BLOCK' undeclared (first use in this function); did you mean 'SIG_ACK'?
  103 |   sigprocmask(SIG_BLOCK, &sigset_, &sigset2_);
      |               ^~~~~~~~~
      |               SIG_ACK
make[1]: *** [<builtin>: hal_posix/hal.o] Error 1
make[1]: Leaving directory '/home/jling/mrubyc/mrubyc-release3.1/src'
make: *** [Makefile:23: mrubyc_lib] Error 2

**Comment by kaz0505** [comment]
I assume that this error occurs because the timer interruption in MINGW64 is different from that in POSIX.
Try selecting the compiler option that does not use timer interruption.

`-DMRBC_NO_TIMER`
