### ISSUE TITLE
mrb_load_string()

### ISSUE THREAD

**Issue by xor256** [mrubyc/mrubyc#17]
Is the planned function of mrb_load_string() ? (and sometimes mrb_load_file(mrb, f); )

Or the only way is to be external compilation.

**Comment by kaz0505** [comment]
mrb_load_string is difficult for mruby/c.
mrb_load_string requires mruby compiler. currently mruby/c does not have compiler, it has vm only.

mrb_load_file is load byte-code from file, so compiler is not necessary.

**Comment by texrg** [comment]
@kaz0505 
I know what is now ;-) but in future or meybe only for testing? 
mrb_load_string() is not neccesary in mrubyc, meybe only in C_test programs?
How big is it?

**Comment by kaz0505** [comment]
mrb_load_string is like a wrapper function of mruby compiler, because mrb_load_string converts ruby source code (string) to byte code.
On the other hand, mrb_load_file is a simple byte code loader, which read a byte code binary and get information for VM execution.

**Comment by xor256** [comment]
@kaz0505 
How join mruby and mrubyc for testing?

```
#include <mruby.h>
#include <mruby/proc.h>

int main(int argc, const char * argv[])
{
  mrb_state *mrb = mrb_open();
  mrbc_context *cxt;
  mrb_value val;
  struct mrb_parser_state *ps;
  struct RProc *proc;

  char code[] = "1 + 1";

  cxt = mrbc_context_new(mrb);
  ps = mrb_parse_string(mrb, code, cxt);
  proc = mrb_generate_code(mrb, ps);
  mrb_pool_close(ps->pool);

  val = mrb_run(mrb, proc, mrb_top_self(mrb));
  mrb_p(mrb, val);

  mrbc_context_free(mrb, cxt);
return 0;
}

```

Where put mrubyc running and how compiling it?

**Comment by xor256** [comment]
Meybe using https://gitter.im for talking about this andmemory allocation?

**Comment by kaz0505** [comment]
I've created https://gitter.im/mrubyc/mrubyc
