### ISSUE TITLE
doc 'How compile'

### ISSUE THREAD

**Issue by wir19** [mrubyc/mrubyc#194]
- in  **/sample_c** is more than thre exacutables and any not named **mrubyc** 

- no file basic_*.mrb in any directory

**Comment by kaz0505** [comment]
The sample_c folder shows several examples of running the mruby/c VM.
The simplest example is sample_include.c, which has the bytecode as a C array.

sample_no_scheduler.c and sample_scheduler.c are standard executions, taking the xxx.mrb file as argument.

To create an mrb file, you need mruby (not mruby/c). mrbc generates the bytecode.

**Comment by srem1** [comment]
documentation https://github.com/mrubyc/mrubyc/blob/master/doc/compile.md need change

**Comment by kaz0505** [comment]
As you noted, the documentation needs to be updated. Thanks.

**Comment by kaz0505** [comment]
[`compile.md`](https://github.com/mrubyc/mrubyc/blob/master/doc/compile.md) updated.
