### ISSUE TITLE
module keyword/support

### ISSUE THREAD

**Issue by m0nt3-q** [mrubyc/mrubyc#203]
Is `module` a feature that would be welcome in the vm? I noticed that it is marked `op_unsupported` and am curious if this is because it's not wanted because of the design goals of the project (small size, small memory consumption)?

**Comment by HirohitoHigashi** [comment]
To keep the footprint small, we decided not to support MODULE.
However, if there are many requests, we will consider supporting it.

**Comment by kaz0505** [comment]
There are plans to design the equivalent of a module function.
Among the functions that the module has, we are planning to select
and implement the functions needed as mruby/c.
