### ISSUE TITLE
logo 

### ISSUE THREAD

**Issue by xor256** [mrubyc/mrubyc#21]
# m  💎  c^_2_

E=m * c^2 but change multiply to symbol ruby
the name of repository /**mrubyc2**
What You think about this?

**Comment by kaz0505** [comment]
Thank you.
we don't have any logos for mrubyc.
let's discuss about logo for this project, later.

**Comment by kaz0505** [comment]
about mruby/c logo, we want to use it for presentations and announcements.
for this purpose, the copyright of the logo is important.

current developer for mruby/c is not so many.
deciding the logo after official release of mruby/c?

**Comment by xor256** [comment]
私の提案は、ASCII文字だけで構成されています。
残りは私に無関心です。
My proposal contains only ASCII characters.
The rest is indifferent to me.
