### ISSUE TITLE
compile error on Renesas CS+

### ISSUE THREAD

**Issue by yamori813** [mrubyc/mrubyc#211]
Sorry use Japanese.

ルネサスのCS+ V8.10.00でRX210のビルドを試しているのですが、以下のエラーが発生します。

(E)	C0520000	mrubyc-release3.3.1\src\c_object.c(934):C0520000:Internal Error.	c_object.c	934	mrubyc.mtpj

このファイル以外はコンパイルできているようです。

資料にあったようにMRBC_NO_TIMERを定義してC99で試しています。

おそらくルネサスオリジナルなCコンパイラーの問題だと思われますが、何かご存知でしたらアドバイスいただけると助かります。

**Comment by yamori813** [comment]
RX210はe2 studioでgccも利用できて、gccではコンパイルできるようなので、gccを使うことにしました。

お騒がせしてすみませんでした。

**Comment by HirohitoHigashi** [comment]
レポート頂きありがとうございます。
私もこの件は把握していて、Renesas のコンパイラの問題であると認識しています。
以前はコンパイルできていました。しかし正確な時期は把握していませんが、最近のmruby/cソースと最近のRX-CCでは、コンパイラが内部エラーで止まるようになってしまいました。
ルネサスのサポート契約はしておらず、正規パスでのサポート依頼ができないため、ちょっとしたツテでこっそり聞いてもらったのですが、コンパイラの開発チームは日本では無いようでして、一応開発チームにも伝えて頂いたようではありますが、望んだ回答はありませんでした。
@yamori813 が一つ前で言われたように、ルネサス配布のgcc なら大丈夫なので、一応これが回避策ということになりそうです。
