### ISSUE TITLE
How creating   sample_c/sample1.c   file?

### ISSUE THREAD

**Issue by mikolaj24** [mrubyc/mrubyc#32]
$ ./mrbc -v
mruby 1.2.0 (2015-11-17)
$mrbc -Bary -osample01.c ../sample_ruby/basic_sample01.rb
i change header to "const uint8_t ary[]"
$make
$./mrubyc_sample
Error: Illegal bytecode.

-----
meybe in mrubyc/sample_c/Makefile add line
MRUBY_COMPILER = ../../mruby/build/host/bin/mrbc

sample1.c : ../sample_ruby/basic_sample01.rb
      MRUBY_COMPILER -Bary [....]

**Comment by kaz0505** [comment]
This error comes from byte order.
Compile with "-E" option:

mrbc **-E** -Bary rubycode.rb

**Comment by mikolaj24** [comment]
working !
-----
diff --git a/sample_c/Makefile b/sample_c/Makefile
index 013406a..1c37029 100644
--- a/sample_c/Makefile
+++ b/sample_c/Makefile
@@ -11,12 +11,16 @@ TARGETS = mrubyc mrubyc_sample mrubyc_concurrent
 CFLAGS = -g -I ../src -Wall -Wpointer-arith
 LDFLAGS = -L ../src
 LIBMRUBYC = ../src/libmrubyc.a
+MRUBY_COMPILER = ../../mruby/build/host/bin/mrbc
 
 all: $(TARGETS)
 
 mrubyc: main.c $(LIBMRUBYC)
        $(CC) $(CFLAGS) $(LDFLAGS) -o $@ main.c $(LIBMRUBYC)
 
+sample01.c : ../sample_ruby/basic_sample01.rb
+       $(MRUBY_COMPILER) -E -Bary -o$@ $<
+
 mrubyc_sample: main_sample.c $(LIBMRUBYC)
        $(CC) $(CFLAGS) $(LDFLAGS) -o $@ main_sample.c $(LIBMRUBYC)
 -----
i get this effect
**$ ./mrubyc_sample**
30
-10
30
no method(**)!
2
-1
