### ISSUE TITLE
some sample update

### ISSUE THREAD

**Issue by mikolaj24** [mrubyc/mrubyc#33]
diff --git a/sample_ruby/basic_sample01.rb b/sample_ruby/basic_sample01.rb
index 207ddcc..d0fce3a 100644
--- a/sample_ruby/basic_sample01.rb
+++ b/sample_ruby/basic_sample01.rb
@@ -11,3 +11,9 @@ b = b / 2
 c = a + b
 puts c
 
+a = 3
+b = 2 ** a
+puts b
+
+c = b * 2 - a - 2
+puts c
diff --git a/sample_ruby/basic_sample05.rb b/sample_ruby/basic_sample05.rb
index eeba72e..9d5b85e 100644
--- a/sample_ruby/basic_sample05.rb
+++ b/sample_ruby/basic_sample05.rb
@@ -4,3 +4,4 @@ for i in 1..10 do
   puts i
 end
 
+(11..19).each {|e| puts e}

-------
for example 
```
# loop
4.times do |a| puts a end
(4..8).each {|e| puts e}
for i in 9..12 do
  puts i
end
```

------
string_sample03.rb

# String

a = "Super "
puts a * 3

puts "This is " + self.to_s + " program"

a << "mrubyc"
puts a

puts "abcdef" <=> "abcde"
puts "abcd".bytesize
puts "żółw".bytesize

-----
.size == .bytesize ? mrubyc not using utf8?

**Comment by kaz0505** [comment]
String#bytesize is not supported, however, it's ok in current version.
