### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by and09** [mrubyc/mrubyc#34]
i get 3 warning:
-----

cc -Wall -Wpointer-arith -g -DMRBC_DEBUG     -c -o c_string.o c_string.c
c_string.c:75:13: warning: unused function 'c_string_idx_get'
      [-Wunused-function]
static void c_string_idx_get(mrb_vm *vm, mrb_value *v)
            ^
1 warning generated.
cc -Wall -Wpointer-arith -g -DMRBC_DEBUG     -c -o c_symbol.o c_symbol.c
c_symbol.c:13:18: warning: implicit declaration of function 'mrbc_string_dup' is
      invalid in C99 [-Wimplicit-function-declaration]
  v->value.str = mrbc_string_dup(vm, sym);
                 ^
c_symbol.c:13:16: warning: incompatible integer to pointer conversion assigning
      to 'char *' from 'int' [-Wint-conversion]
  v->value.str = mrbc_string_dup(vm, sym);
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.

**Comment by kaz0505** [comment]
Solved in previous update.
