### ISSUE TITLE
Calling mrbc_release when returning C method

### ISSUE THREAD

**Issue by mimaki** [mrubyc/mrubyc#48]
I noticed that C extension library was being created.

In the method of the C extension class library, the **SET_XXX_VALUE** macro is used to specify the return value.

The reference counter is supported after version 1.1, and it is necessary to release self (--ref_count) stored in **v[0]** before setting the return value.

```
static void c_hoge(mrb_vm *vm, mrb_value v[], int argc)
{
   mrbc_release(v);    /* I do not want to call this */
   SET_INT_RETURN(0);
}
```

It is hard for the library developer to call this **mrbc_release()** call, and if you forget to call, the self's reference counter will continue to increase and become a fatal situation.

I think that calling **mrbc_release()** should be included in the **SET_XXX_RETURN** macro.

Please consider it.

**Comment by kaz0505** [comment]
I agree with your proposal. Usually there is `mrb_release` near `SET_*_RETURN`.

**Comment by mimaki** [comment]
Thank you.
I will change and PR.

**Comment by mimaki** [comment]
close
