### ISSUE TITLE
benchmark and memory ussage

### ISSUE THREAD

**Issue by texrg** [mrubyc/mrubyc#5]
Is possible to write some scripts to count:
benchmark
$ time ./mrubyc_sample 
real    0m0.001s
user    0m0.000s
sys 0m0.001s
(but not only once time)

and memory usage:
$memory_usage ./mrubyc_sample 
min, max

I don't know how writing this

**Comment by vessi** [comment]
I can answer regarding memory usage. `mruby/c` currently does not use dynamic memory allocation, so you should use `size` from gcc or clang package and take a look at totals of _data segment.

e.g. for me it's next:

```
$> size -m mrubyc                                                                                                                                                                   
Segment __PAGEZERO: 4294967296
Segment __TEXT: 20480
	Section __text: 18166
	Section __stubs: 60
	Section __stub_helper: 116
	Section __cstring: 374
	Section __const: 5
	Section __unwind_info: 72
	total 18793
Segment __DATA: 36864
	Section __nl_symbol_ptr: 16
	Section __got: 8
	Section __la_symbol_ptr: 80
	Section __common: 1064
	Section __bss: 32352
	total 33520
Segment __LINKEDIT: 16384
total 4295041024
```

`_text` segment is program itself, and `_data` segment in short words is memory that is statically allocated for operation of program. So for my build of mruby/c it's ~32Kb.
If memory management will be changed to dynamic (I'm experimenting with this) - we should use `valgrind` utility to get total allocations number.

**Comment by texrg** [comment]
and what about benchmark?

**Comment by vessi** [comment]
you can simply change `main_sample.c` code to execute bytecode 1kk times, for example.

**Comment by texrg** [comment]
and how count time?
this is not simple. How count number operation, Array operation.
system time etc. look up i write example

in ruby exist

require 'benchmark'

n = 50000
Benchmark.bm do |x|
  x.report { for i in 1..n; a = "1"; end }
  x.report { n.times do   ; a = "1"; end }
  x.report { 1.upto(n) do ; a = "1"; end }
end

how using this?

**Comment by vessi** [comment]
currently you have no way to use `Benchmark` class (or something with similar functionality) in mruby/c. look, 56% of ruby opcodes are not implemented in mruby/c virtual machine yet - so subset of ruby language is very limited. there is no sense to do any benchmarks currently until at least full functionality of ruby virtual machine will be developed.

but if you really want to do benchmarks for some reason - you need to look for way to benchmark c code. I think that [this answer on StackOverflow](http://stackoverflow.com/a/2349941/1214286) is a good starting point.

**Comment by xor256** [comment]
when I add opcodes implementation I would like to know is better or no.

where is list all opcodes? Is possible to automaticaly show in image how many opcodes working?

**Comment by kaz0505** [comment]
In mruby/c 2.0, the performance in execution and requirements of resources are updated.
