### ISSUE TITLE
array and hash

### ISSUE THREAD

**Issue by texrg** [mrubyc/mrubyc#6]
I read source code.
Is possible to using one Array functions to all arrays in mruby?
in class.c is find_method etc. Is possible to using one array mini lib to whole project?
in wich places are using array and hash ?

**Comment by kaz0505** [comment]
I found the problem that it's impossible to find Array methods from other classes.
I'll export the array functions, which are implemented as inline functions now, and
make them to be accessible.

**Comment by texrg** [comment]
is possible to using array|hash function to kernel vm?
for example https://github.com/mrubyc/mrubyc/blob/master/src/symbol.c hash of symbols. is posible to using this same functions to c_hash.c and symbol find, push etc?

**Comment by kaz0505** [comment]
Supported in current version.
