### ISSUE TITLE
NilClass#to_i should be 0

### ISSUE THREAD

**Issue by hasumikin** [mrubyc/mrubyc#63]
### sample code
    nil.to_i

### expected
    0

### actual
    No method. Class:NilClass Method:to_i

### there is a work around though...
```
class NilClass
  def to_i
    0
  end
end
```

**Comment by HirohitoHigashi** [comment]
Thank you for your advice.
I implemented Nil#to_i by C language.
Can you check this commit.
https://github.com/mrubyc/mrubyc/blob/20ffbbef59d6d96f3dc0205eb4b7ba413f767fe0/src/class.c

**Comment by hasumikin** [comment]
@HirohitoHigashi sorry to be late.
to_i, to_a, to_h and to_f all look good to me. thank you!
