### ISSUE TITLE
void * have no size, meybe change to unsigned char* or other sized pointer?

### ISSUE THREAD

**Issue by xor256** [mrubyc/mrubyc#7]
vm.c: In function ‘find_irep_symbol’:
vm.c:38:5: error: pointer of type ‘void _’ used in arithmetic [-Wpointer-arith]
   p += 4;
     ^
vm.c:41:7: error: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
     p += 2+s+1;   // size(2 bytes) + symbol len + '\0'
       ^
vm.c:41:5: error: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
     p += 2+s+1;   // size(2 bytes) + symbol len + '\0'
     ^
vm.c:44:11: error: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
   return p+2;  // skip size(2 bytes)
           ^
vm.c: In function ‘vm_run_step’:
vm.c:1078:45: error: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
   uint8_t *p = (uint8_t *)(vm->pc_irep->code+vm->pc_4);

**Comment by kaz0505** [comment]
Thank you.

How about using uint8_t * instead?
p points to each byte in mruby bytecode.

**Comment by vessi** [comment]
I also think that `uint8_t *` should be more applicable in this case.
