### ISSUE TITLE
Cannot call self method from Array#each block

### ISSUE THREAD

**Issue by hiroeorz** [mrubyc/mrubyc#71]
I am testing on [Wio 3G](https://github.com/SeeedJP/Wiki/blob/master/Wio_cell_lib_for_Arduino/hardware-ja.md)

### NG Sample.

```ruby
class MyClass

  def my_loop(array)
    array.each do |v|
      tara(v)  # self.tara is same result
    end
  end

  def tara(val)
    val
  end

end

my = MyClass.new
my.my_loop([1, 2, 3])
```

=> No Method Error

### OK Sample

```ruby
class MyClass

  def my_loop(array)
    myself = self

    array.each do |v|
      myself.tara(v)
    end
  end

  def tara(val)
    val
  end

end

my = MyClass.new
my.my_loop([1,2,3])
```

=> OK

**Comment by kaz0505** [comment]
I see this problem as you say.
I'll check and fix it.

**Comment by kaz0505** [comment]
Now I'm fixing this problem.
I'm sorry for making wait so long.

**Comment by hasumikin** [comment]
@kaz0505
it's not fixed yet.
Can be closed if this test passes: https://github.com/mrubyc/mrubyc/pull/79/files

**Comment by hasumikin** [comment]
@hiroeorz I think It's been fixed. Please check

**Comment by hiroeorz** [comment]
this issue is fixed. Thanks! 🎉
