### ISSUE TITLE
I'm newbie

### ISSUE THREAD

**Issue by xor256** [mrubyc/mrubyc#9]
I'm starting using github. How I can put my code to repository?

I'm configure propertly
$ ssh -T git@github.com
Hi xor256! You've successfully authenticated, but GitHub does not provide shell access.

but

$ git push
ERROR: Permission to mrubyc/mrubyc.git denied to xor256.
fatal: Could not read from remote repository.

**Comment by vessi** [comment]
You need to fork original repository and push in it. After this you should do pull-request to ask original repository maintainer to merge your code in upstream repository. [This link](https://help.github.com/categories/collaborating-on-projects-using-issues-and-pull-requests/) will be useful for you

**Comment by xor256** [comment]
ok

**Comment by xor256** [comment]
is possible to delete this issue ?

**Comment by vessi** [comment]
@xor256 you need to just close it. Button is located below comment field (near green comment button)
